version: 2
update_configs:
  - package-ecosystem: "gradle"
    directory: "/AccessibilityInsightsForAndroidService/app/"
    labels:
      - "category: engineering"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
