# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger: none
pr: none

jobs:
    - job: 'gradlew_build_publish'

      pool:
          vmImage: 'windows-latest'

      steps:
          - script: | 
              echo This build requires you to override APK_VERSION_NAME and APK_VERSION_CODE vars at queue-time
              exit 1
            displayName: ensure version vars are set
            failOnStderr: true
            condition: or(eq(variables['APK_VERSION_NAME'], 'REPLACE_ME'), eq(variables['APK_VERSION_CODE'], 'REPLACE_ME'))

          - task: Gradle@2
            displayName: build and test ai-android service
            inputs:
              workingDirectory: '$(system.defaultWorkingDirectory)/AccessibilityInsightsForAndroidService'
              gradleWrapperFile: 'AccessibilityInsightsForAndroidService/gradlew'
              gradleOptions: '-Xmx3072m'
              options: -S -PapkVersionCode=$(APK_VERSION_CODE) -PapkVersionName=$(APK_VERSION_NAME)
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'build'

          - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
            displayName: 'sign release apk with ESRP CodeSigning'
            inputs:
              ConnectedServiceName: 'Accessibility Insights for Android Service AAD APP Id'
              FolderPath: '$(system.defaultWorkingDirectory)/AccessibilityInsightsForAndroidService/app/build/outputs/apk/release'
              Pattern: '*.apk'
              signConfigType: inlineSignParams
              inlineOperation: |
                [
                        {
                            "KeyCode" : "CP-458288-Java",
                            "OperationCode" : "AndroidSign",
                            "Parameters" : {},
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        },
                        {
                            "KeyCode" : "CP-458288-Java", 
                            "OperationCode" : "JavaVerify",
                            "Parameters" : {},
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        }
                ]

          - task: PublishPipelineArtifact@1
            displayName: publish apk folder as artifact
            inputs:
              artifactName: 'apk'
              targetPath: '$(system.defaultWorkingDirectory)/AccessibilityInsightsForAndroidService/app/build/outputs/apk/'

          - task: CopyFiles@2
            displayName: prepare license and notice to publish as artifact
            inputs:
              sourceFolder: '$(system.defaultWorkingDirectory)'
              contents: |
                LICENSE
                NOTICE.txt
              targetFolder: '$(build.artifactstagingdirectory)/terms'

          - task: PublishPipelineArtifact@1
            displayName: publish license and notice as artifact
            inputs:
              artifactName: 'terms'
              targetPath: '$(build.artifactstagingdirectory)/terms'

          - script: type $(system.defaultWorkingDirectory)\AccessibilityInsightsForAndroidService\app\build\outputs\apk\release\output.json
            displayName: print out generated release APK info