# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
  - main

jobs:
  - job: 'gradlew_build'

    pool:
        vmImage: 'windows-latest'

    steps:
      - task: Gradle@2
        displayName: build and test dev ai-android service
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/AccessibilityInsightsForAndroidService'
          gradleWrapperFile: 'AccessibilityInsightsForAndroidService/gradlew'
          gradleOptions: '-Xmx3072m'
          options: -S
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'

      - task: CopyFiles@2
        displayName: (lint-results) copy lint-results files to artifact staging
        condition: succeededOrFailed()
        inputs:
          contents: |
            lint-results.html
            lint-results.xml
          sourceFolder: '$(system.defaultWorkingDirectory))/AccessibilityInsightsForAndroidService/app/build/reports'
          targetFolder: '$(build.artifactstagingdirectory)/lint-results'

      - task: PublishPipelineArtifact@1
        displayName: (lint-results) publish lint-results artifact
        condition: succeededOrFailed()
        inputs:
          artifactName: 'lint-results'
          targetPath: '$(build.artifactstagingdirectory)/lint-results'

      - script: node $(system.defaultWorkingDirectory)/pipeline/verify-notice-contents.js
        displayName: verify NOTICE.html content matches lockfile
